#  -*- mode: sh; -*-
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

eval `dircolors -b`
export PATH=$PATH:$HOME/bin:$HOME/local/bin

# Editors
export EDITOR="emacsclient -c"
export VISUAL="emacsclient -c"
export ALTERNATE_EDITOR=""

#colored grep
export GREP_COLOR="1;33"
alias grep='grep --color=auto'

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

if [ -f ~/local/liquidprompt/liquidprompt ]; then
    unset PROMPT_COMMAND
    source ~/local/liquidprompt/liquidprompt
fi

shopt -s cdspell
shopt -s cdable_vars
shopt -s checkhash
shopt -s checkwinsize
shopt -s sourcepath
shopt -s no_empty_cmd_completion
shopt -s cmdhist
shopt -s histappend histreedit histverify

export HISTSIZE=2000
export HISTCONTROL=erasedups

alias more='less'
export PAGER=less


if [[ -f $HOME/.ssh/ssh_cd ]]
then
    cd -P $(<$HOME/.ssh/ssh_cd)
    rm $HOME/.ssh/ssh_cd
fi

source ~/.aliases
source ~/.localrc
