#!/bin/bash

#
# ~/.profile
#
# Executed by startx (run your window manager from here)
#
xset -b

urxvtd -q -o -f

USRRESOURCES=$HOME/.Xresources

xrdb -merge ~/.Xresources

[[ -f ~/.Xresources-local ]] && xrdb -merge ~/.Xresources-local
numlockx on&
xmodmap ~/.xmodmap &

export EDITOR="emacsclient -c"
export VISUAL="emacsclient -c -n"
export ALTERNATE_EDITOR=""

export PATH=$PATH:~/bin:/usr/local/bin

export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'
uim-xim &
export XMODIFIERS='@im=uim'

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

start-pulseaudio-x11
