# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=20000
SAVEHIST=10000
setopt appendhistory autocd beep extendedglob nomatch notify
setopt share_history
setopt hist_ignore_dups
setopt hist_expire_dups_first
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/bfahy/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# cool options
setopt correct

#colored grep
export GREP_COLOR="1;33"
alias grep='grep --color=auto'

export LP_PS1_POSTFIX="
>"


#emacs likes this
export TERM=xterm-256color

if [ -f ~/local/liquidprompt/liquidprompt ]; then
    source ~/local/liquidprompt/liquidprompt
fi

eval `dircolors -b`


# Bash-like navigation
autoload -U select-word-style
select-word-style bash

#allow '#' as comments inline
setopt interactivecomments

typeset -A key

key[Home]=${terminfo[khome]}

key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

# setup key accordingly
[[ -n "${key[Home]}"     ]]  && bindkey  "${key[Home]}"     beginning-of-line
[[ -n "${key[End]}"      ]]  && bindkey  "${key[End]}"      end-of-line
[[ -n "${key[Insert]}"   ]]  && bindkey  "${key[Insert]}"   overwrite-mode
[[ -n "${key[Delete]}"   ]]  && bindkey  "${key[Delete]}"   delete-char
[[ -n "${key[Up]}"       ]]  && bindkey  "${key[Up]}"       up-line-or-history
[[ -n "${key[Down]}"     ]]  && bindkey  "${key[Down]}"     down-line-or-history
[[ -n "${key[Left]}"     ]]  && bindkey  "${key[Left]}"     backward-char
[[ -n "${key[Right]}"    ]]  && bindkey  "${key[Right]}"    forward-char
[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   beginning-of-buffer-or-history
[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}" end-of-buffer-or-history

source ~/.zaliases

### SHOULD ONLY BE IN .zshenv but stupid arch overwites path after it is loaded
typeset -U path
path=(~/local/bin ~/bin /usr/local/bin $path)


if [ -f ~/.localrc ]; then
source ~/.localrc
fi
